### ISSUE TITLE
Discussing pathfinding API

### ISSUE THREAD

**Issue by AgostinoSturaro** [libgdx/gdx-ai#7]
> EDIT by davebaol
> - Pathfinding [TODO List](https://github.com/libgdx/gdx-ai/issues/7#issuecomment-61283559)
> - Pathfinding [wiki page](https://github.com/libgdx/gdx-ai/wiki/Pathfinding) (to be finished)

Hello, now that you have your own extension, maybe you can start considering an A\* implementation to go together with that wonderful steering, right? :)

**Comment by Nauktis** [comment]
I am using the Pathfinding api in my current project.
I'm facing a challenge and don't know if it is possible with the current api.
My target node is a non walkable node but I want to find a path to any of its connected node.
How should I go about this?

**Comment by davebaol** [comment]
@Nauktis 
Hmmm... so your target node is actually a set whose nodes are specified by a certain criteria, right? 
Probably the neatest way to support your requirement is to change the API in order to pass an `endNodeTest` to the `PathFinder.search` methods in place of the endNode.
I'll look into it deeper soon (hopefully).

**Comment by davebaol** [comment]
Just to clarify what I mean
````java
public interface GoalHandler<N> {

	/** Checks the given node to see if it is a goal node.
	 * @param node the node to test
	 * @return {@code true} if the given node is a goal node; {@code false} otherwise */
	public boolean isGoal (N node);

	/** Calculates the estimated cost to reach the goal from the given node.
	 * <p>
	 * This method is the heuristic function that pathfinding algorithms use to choose the node that is most likely to lead to the
	 * optimal path. The notion of "most likely" depends on the heuristic implementation. If the heuristic is accurate, then the
	 * algorithm will be efficient. If the heuristic is terrible, then it can perform even worse than other algorithms that don't
	 * use any heuristic function such as Dijkstra.
	 * @param node the node to estimate the cost for
	 * @return the estimated cost */
	public float estimateCost (N node);
}
````
What do you think?

PS:
Any idea of a better name for the `GoalHandler` class? I'm not fully convinced by the Handler part. :expressionless:

**Comment by Nauktis** [comment]
Thanks for the amazingly fast response davebaol :)
Your idea seems to allow for a lot of flexibility and is definitely addressing my need.
Any reason to have moved the heuristic in?
If you leave the heuristic out you can probably call it GoalPredicate (?)

**Comment by davebaol** [comment]
@Nauktis 
Yeah I moved the heuristic there because it heavily depends on the goal.
I mean, each time you have to calculate a new path you have to specify the new goal. Both the heuristic and the test must know it. For example, a very simple implementation might be like that
````java
public class MyGoalHandler implements GoalHandler<TiledNode> {
    private TiledNode endNode;

    public MyGoalHandler() {
    }

    public void setEndNode (TiledNode node) {
        this.endNode = endNode;
    }

    @Override    
    public boolean isGoal (TiledNode node) {
        return node == endNode;
    }

    @Override    
    public float estimateCost (TiledNode node) {
        return Math.abs(endNode.x - node.x) + Math.abs(endNode.y - node.y);
    }
}
````
Typical usage
````java
    myGoalHandler.setEndNode(endNode);
    pathFinder.search(startNode, myGoalHandler, outPath);
````

**Comment by Nauktis** [comment]
Makes a lot of sense indeed.
Can't wait to have it included and play with it (pathfinding to an area, get close enough to something, etc.).

**Comment by davebaol** [comment]
Maybe `GoalController` is a more appropriate name. Thoughts?

**Comment by davebaol** [comment]
@Nauktis 
It looks like there is a problem with the proposed API change and hierarchical pathfinding which needs the actual end node to convert nodes between levels, see https://github.com/libgdx/gdx-ai/blob/master/gdx-ai/src/com/badlogic/gdx/ai/pfa/HierarchicalPathFinder.java#L75

A possible (easy) solution could be to add a `getActualEndNode` to the `GoalController` interface that will be used by hierarchical pathfinding algorithm to switch between graph levels. However, this means that hierarchical pathfinder is limited to 1 node to change level.

Actually this is kinda a ugly hack that makes no sense in lots of situations because usually a goal represented by a set of nodes is based on quality criteria rather than neighborhood criteria. For example, in chess, the goal is to reach a state called “checkmate” where the opponent’s king is under attack and can’t escape. Obviously all these checkmate states are not neighbors in the graph (they are not directly connected).

This makes me hesitant.

**Comment by Nauktis** [comment]
@davebaol 
I fully understand your concern. Maybe the goal should always be a node like it is the case for the moment. But the API could take an optional GoalController that would only have one method isGoodEnough(currentNode). If this method returns true, that would say the current path is good enough even though the destination node hasn't been reached. And the pathfinding would stop with the current path. Would that be a less obstructive approach?

**Comment by davebaol** [comment]
@Nauktis 
Just created a [new issue](https://github.com/libgdx/gdx-ai/issues/24) to keep track of the enhancement.

I think it will be postponed after 1.5.0 that should come out soon.

**Comment by davebaol** [comment]
gdx-ai 1.5.0  has been just released :smile:

**Comment by adam-law** [comment]
Hi,

Great work on this library. I've been able to implement it for use in my square and hex grids, where it computes the path of an object the size of a grid cell. My question is, what is the correct approach for objects larger than a grid cell (e.g. 2x2, 3x3)? Right now, larger objects "pass through" "tunnels" that are 1x1 wide, because the computation only figures in the 1x1 starting cell to the end node.

Off the top of my head, I was (naively) thinking that I would need to create different graphs based on the "master" graph, accounting for the possible entity sizes. For example, a graph for 2x2 sized entities would start from master graph's 0, 0 cell and encompass cells (0, 1), (1, 0), and (1, 1). If one of these cells is of a "blocking" type, the 2x2 graph's 0,0 node, would then be marked as "blocked". Any extraneous nodes of the 1x1 graph that don't fit into the 2x2 one, will be declared untraversable as well. 

I'm hesitant to implement the (naive) idea, thinking that you might have a better one, or there is already an existing solution here that I missed. 

Any advice would be appreciated :)

**Comment by davebaol** [comment]
@adam-law 
You might work at the heuristic level with just one graph. If the heuristic function is somehow aware of the size of the character you're calculating the path for, you can simply return `Float.POSITIVE_INFINITE` when the cell cannot be traversed. 
This should do the trick.

**Comment by adam-law** [comment]
Thanks for the quick reply :)

I guess you're saying that, in the heuristic, I should do the checking of the entity size, versus some information regarding size on that node? Something like the clearance algorithm? Or were you pertaining to something else? Sorry for the questions, I'm still very new to game development XD

**Comment by davebaol** [comment]
@adam-law 
Yeah that's what I meant.
Keep in mind that the heuristic should be as fast as possible. So it would be advisable to precalculate the size of the passage for each node in the graph.

**Comment by entangledloops** [comment]
https://github.com/adam-law
It's quite common to perform search on a coarse grid of a larger size, and
if you find no path then refine the search to a smaller space. As for grid
alignment, that's a parameter that will never be "generally correct" for
all maps or positions, so it doesn't matter so much. You can try
re-aligning and searching again.
On Fri, Sep 18, 2015 at 9:36 AM davebaol <notifications@github.com> wrote:

> @adam-law <https://github.com/adam-law>
> Yeah that's what I meant.
> Keep in mind that the heuristic should be as fast as possible. So it would
> be advisable to precalculate the size of the passage for each node in the
> graph.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libgdx/gdx-ai/issues/7#issuecomment-141370945>.
>
-- 
Stephen Dunn
http://www.entangledloops.com

Setem Technologies
http://www.setemtech.com
12 Kent Way, Suite 210
Newbury, MA  01922
ph: +1 (617) 997.0000
fx:  +1 (617) 995.0890

**Comment by adam-law** [comment]
Great advice guys. I appreciate it. Cheers!

**Comment by davebaol** [comment]
Commit f5ef1a9b4601560d490ca74b26cc2ae532c6e185 should make the API slightly simpler

**Comment by piotrekuczy** [comment]
Hello,

Could somebody help me how to use Path Smoothing?

( https://github.com/libgdx/gdx-ai/wiki/Path-Smoothing )

I need some code example.

**Comment by davebaol** [comment]
@piotrekuczy 
Sure, you can look at [this](https://github.com/libgdx/gdx-ai/blob/master/tests/src/com/badlogic/gdx/ai/tests/pfa/tests/FlatTiledAStarTest.java) 

Basically, you have to create the pathSmoother once, then call `pathSmoother.smoothPath(path);`
To create the pathSmoother you need an implementation of RaycastCollisionDetector which performs line of sight between nodes.

**Comment by piotrekuczy** [comment]
ok, i have this:

SmoothableGraphPath<MyNode, Vector2> smoothPath;
PathSmoother<MyNode, Vector2> pathSmoother;

and i have cannot instantiate error with this line:

smoothPath = new SmoothableGraphPath<MyNode, Vector2>();

what is wrong?

**Comment by davebaol** [comment]
Well, my crystal ball is broken... What about showing your code and stack trace? :smiley:

**Comment by piotrekuczy** [comment]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.Error: Unresolved compilation problem: 
	Cannot instantiate the type SmoothableGraphPath<MyNode,Vector2>

	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.Error: Unresolved compilation problem: 
	Cannot instantiate the type SmoothableGraphPath<MyNode,Vector2>

	at com.postpunkgames.SceneEditor.create(SceneEditor.java:169)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by davebaol** [comment]
Hmmm.... "Unresolved compilation problem" means that your code does not even compile correctly. You should first fix compile errors in source code.

**Comment by piotrekuczy** [comment]
i know, but why this line is good:
```
SmoothableGraphPath< MyNode, Vector2> smoothPath;
```
but this line isn't? :
```
smoothPath = new SmoothableGraphPath< MyNode, Vector2 >();
```

**Comment by davebaol** [comment]
Because `SmoothableGraphPath` is an interface, so you cannot instantiate it.
You have to create a concrete class which implements that interface.

**Comment by piotrekuczy** [comment]
Thank you. Now i have a problem because my graph is no grid based (like yours examples) - my nodes are a polygon vertices.
Could you help me how to implement MyRaycastCollisionDetector and MySmoothPath in my code?

This is my classes:

**main game** class

```
// pathfinding

	MyGraph mGraph;
	IndexedAStarPathFinder<MyNode> mPathFinder;
	DefaultGraphPath<MyNode> mPath;
	ManhattanDistanceHeuristic mHeuristic;
		
// pathsmoothing
		
	MyRaycastCollisionDetector raycastCollisionDetector;
	MySmoothPath smoothedPath;
	PathSmoother<MyNode, Vector2> pathSmoother;

	...


// pathfinding

	nodes = new Array<MyNode>();
	mPath = new DefaultGraphPath<MyNode>();
	mHeuristic = new ManhattanDistanceHeuristic();
		
// smooth path
		
	smoothedPath = new MySmoothPath();
	raycastCollisionDetector = new MyRaycastCollisionDetector();
	pathSmoother = new PathSmoother<MyNode, Vector2>(raycastCollisionDetector);
```

**MySmoothPath** class

```
import java.util.Iterator;
import com.badlogic.gdx.ai.pfa.SmoothableGraphPath;
import com.badlogic.gdx.math.Vector2;

public class MySmoothPath implements SmoothableGraphPath<MyNode, Vector2> {

	public MySmoothPath() {
		// TODO Auto-generated constructor stub
	}

	@Override
	public int getCount() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public MyNode get(int index) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void add(MyNode node) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void clear() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void reverse() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Iterator<MyNode> iterator() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Vector2 getNodePosition(int index) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void swapNodes(int index1, int index2) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void truncatePath(int newLength) {
		// TODO Auto-generated method stub
		
	}

}
```

**MyRaycastCollisionDetector** class:

```
import com.badlogic.gdx.ai.utils.Collision;
import com.badlogic.gdx.ai.utils.Ray;
import com.badlogic.gdx.ai.utils.RaycastCollisionDetector;
import com.badlogic.gdx.math.Vector2;

public class MyRaycastCollisionDetector implements RaycastCollisionDetector<Vector2> {

	public MyRaycastCollisionDetector() {
		// TODO Auto-generated constructor stub
	}

	@Override
	public boolean collides(Ray<Vector2> ray) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean findCollision(Collision<Vector2> outputCollision, Ray<Vector2> inputRay) {
		// TODO Auto-generated method stub
		return false;
	}

}
```

**ManhattanDistanceHeuristic** class

```
import com.badlogic.gdx.ai.pfa.Heuristic;

public class ManhattanDistanceHeuristic implements Heuristic<MyNode> {

	public ManhattanDistanceHeuristic() {
	}

	@Override
    public float estimate(MyNode node, MyNode endNode) {
        return Math.abs(endNode.mX - node.mX) + Math.abs(endNode.mY - node.mY);
    }

}
```

**Comment by davebaol** [comment]
Oh for navmesh pathfinding with gdx-ai with you might want to look at the open source project [GdxDemo3D](https://github.com/jsjolund/GdxDemo3D).

**Comment by piotrekuczy** [comment]
in this project there is no PathSmoother

**Comment by davebaol** [comment]
Well, there's no `PathSmoother` because that project performs path smoothing through the [simple stupid funnel algorithm](http://digestingduck.blogspot.it/2010/03/simple-stupid-funnel-algorithm.html).

See the `Funnel` inner class in  [NavMeshPointPath.java](https://github.com/jsjolund/GdxDemo3D/blob/master/core/src/com/mygdx/game/pathfinding/NavMeshPointPath.java)

**Comment by piotrekuczy** [comment]
I will read this, thanks. So there is no working example of PathSmoother with navmesh?

**Comment by davebaol** [comment]
Not that I know of

**Comment by implicit-invocation** [comment]
@davebaol 
I used the precompiled Java code from `hxDaedalus` and wrote a very thin layer on top of it to provide an easy to setup 2D polygonal pathfinding.

https://github.com/implicit-invocation/jwalkable

Any chance for merging?

**Comment by assofohdz** [comment]
Polygonal pathfinding would make gdx-ai a go-to library! 👍

**Comment by dushechka** [comment]
> @davebaol
> I used the precompiled Java code from `hxDaedalus` and wrote a very thin layer on top of it to provide an easy to setup 2D polygonal pathfinding.
> 
> https://github.com/implicit-invocation/jwalkable
> 
> Any chance for merging?

So, what's up with merging? I couldn't find it in the GDX.
